### ISSUE TITLE
Not possible to redeem all DAI (without getting into some complex Math)

### ISSUE THREAD

**Issue by chrishobcroft** [empowerthedao/compound-aragon-app#3]
I would like to redeem my entire supply of DAI being supplied by the DAO to Compound.

This is what I do:

1. Go to the [Compound app in the etd DAO on rinkeby](https://rinkeby.aragon.org/#/etd/0x6e2229174608857bb228149f71c37b2cad568fae)

2. See that my supply balance is 10.000003 DAI

![image](https://user-images.githubusercontent.com/2212651/64339652-c4a2af80-cfe4-11e9-80a3-f30dc50672a4.png)

3. Create and pass a vote to redeem 10.000003 DAI

4. See that my supply balance is 0.000003 DAI

![image](https://user-images.githubusercontent.com/2212651/64340019-835ecf80-cfe5-11e9-9c4e-b4adabd16abe.png)

5. Create and pass a vote to redeem 0.000003 DAI

6. See that my supply balance is shown as 0 DAI

![image](https://user-images.githubusercontent.com/2212651/64340123-b608c800-cfe5-11e9-92a3-413aead1c682.png)

7. See that in etherscan, my Agent app still has some cDAI (0.0000003) unredeemed:

![image](https://user-images.githubusercontent.com/2212651/64340205-e51f3980-cfe5-11e9-88d9-07c2e8ae43b7.png)

What amount of DAI do I put into the app to redeem all of it?

Perhaps there can be some kind of ability to "redeem everything", or maybe to not round the "Supply Balance", meaning that you can always copy / paste the full amount if you desire.

**Comment by willjgriff** [comment]
I'll add a 'set max' button next to the input of the redeem amount. I'm not going to increase the decimals visible for the `Supply Balance:` though. Other apps use a max of 2 decimals so I think 6 is more than enough.

Also, the supply balance is not rounded, it's truncated to prevent issues with copying. The reason there is some left over after you redeem is because in the transaction when you redeem, the protocol first accrues interest owed to you then redeems the amount you specified. The interest accrued in that transaction is not withdrawn as it's not in the amount originally specified.

**Comment by chrishobcroft** [comment]
Closed, and yes, the fact that interest accrues in the time it takes to pass a vote is funny, and probably unavoidable...
